### ISSUE TITLE
Next: build hook is wrong

### ISSUE THREAD

**Issue by flovntp** [platformsh/cli#151]
When using `project:init` command on a Next.js stack, it generates the following: 
```
applications:
  app:
    hooks:
      # The build hook is run after any build flavor.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#build-hook
      build: |
        set -eux
        npm i    
```
but it should be 
```
applications:
  app:
    hooks:
      build: |
        set -eux
        npm i
        npm exec next build
```
