### ISSUE TITLE
Github Actions failing after update to 4.1.1

### ISSUE THREAD

**Issue by ptmkenny** [platformsh/cli#46]
I run some behat tests on my platform site with Github Actions, and the builds just started failing a few minutes ago.

This is the error:

```
Error: Unable to process file command 'env' successfully.
Error: Invalid format '[https://www.branch-example-***.us-3.platformsh.site/](https://www.branch-example-%2A%2A%2A.us-3.platformsh.site/)'
```

Here's the action. It's the final step that is giving the error.

```
    # platform CLI + drush
    - name: "Set the platform drush alias."
      shell: bash
      run: |
        echo "PLATFORMSH_DRUSH_ALIAS=@site-aliases.anata.$BRANCH_NAME" >> $GITHUB_ENV
        echo "platform.sh drush alias: $PLATFORMSH_DRUSH_ALIAS"
    - name: "Install platform CLI."
      shell: bash
      run: curl -sS https://platform.sh/cli/installer | php
    # https://stackoverflow.com/a/68214331
    - name: "Add platform CLI to path."
      shell: bash
      run: echo "/home/runner/.platformsh/bin" >> $GITHUB_PATH
    - name: "Set the platform URL as an environment variable."
      shell: bash
      env:
        PLATFORMSH_CLI_TOKEN: ${{ inputs.platformsh_cli_token }}
      run: echo "PLATFORMSH_URL=$(platform url --pipe -p $PLATFORMSH_SITE_ID -e $BRANCH_NAME | grep 'https://www')" >> $GITHUB_ENV
```

This was working as recently as yesterday with 4.1.0.  I haven't made any code changes to this action, so I'm assuming the 4.1.1 update broke things somehow.  Any ideas?
